const recipesData = [
    {
      name: "Butter Chicken",
      chef: "Chef Raj",
      totalRatings: 1200,
      avgRating: 4.9,
      uploadedOn: "2024-02-10",
      mealType: "Dinner",
      dishType: "Curry",
      testKitchenApproved: true,
      contestWinner: true,
      featured: true,
      description: "A rich and creamy tomato-based curry with tender pieces of chicken.",
      imgUrl: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQ5KbltsmL-aCgIAKHeF7bGpd4TZeqAFoye2CeaeTqS1E8xWBMBIf0n7ADWorNTqN7dkudjEnsKyu_MfegzjLCWGwZIo2a8I1vUoVIn9bw"
    },
    {
      name: "Paneer Tikka",
      chef: "Chef Anjali",
      totalRatings: 850,
      avgRating: 4.7,
      uploadedOn: "2024-03-05",
      mealType: "Dinner",
      dishType: "Appetizer",
      testKitchenApproved: true,
      contestWinner: false,
      featured: true,
      description: "Spiced and grilled paneer cubes served with mint chutney.",
      imgUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRj_w-NpRCnX_t4ro-6LXLqPPAQA9F_VQljbQ&s'
    },
    {
      name: "Masala Dosa",
      chef: "Chef Kumar",
      totalRatings: 950,
      avgRating: 4.8,
      uploadedOn: "2024-01-20",
      mealType: "Breakfast",
      dishType: "South Indian",
      testKitchenApproved: true,
      contestWinner: false,
      featured: true,
      description: "Crispy fermented rice crepe filled with spiced potato filling.",
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKGuH0Z2U9bDKyJKNFKEStBjMy2uI19Jhgfg&s"
    },
    {
      name: "Hyderabadi Biryani",
      chef: "Chef Sameer",
      totalRatings: 1300,
      avgRating: 5.0,
      uploadedOn: "2024-02-25",
      mealType: "Dinner",
      dishType: "Rice Dish",
      testKitchenApproved: true,
      contestWinner: true,
      featured: true,
      description: "Aromatic basmati rice cooked with marinated meat and Indian spices.",
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXbg9_BJKxH4-h9FWkNXqEHn8I0aK2Ruhmfw&s"
    },
    {
      name: "Chole Bhature",
      chef: "Chef Meera",
      totalRatings: 890,
      avgRating: 4.7,
      uploadedOn: "2024-03-02",
      mealType: "Breakfast",
      dishType: "North Indian",
      testKitchenApproved: true,
      contestWinner: false,
      featured: true,
      description: "Spicy chickpea curry served with fluffy deep-fried bread.",
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqFHMCZ7CnPo5NEqxOwyckoODeiRyLxYmiHg&s"
    },
    {
      name: "Rasam",
      chef: "Chef Narayan",
      totalRatings: 770,
      avgRating: 4.6,
      uploadedOn: "2024-02-28",
      mealType: "Lunch",
      dishType: "Soup",
      testKitchenApproved: true,
      contestWinner: false,
      featured: false,
      description: "A tangy South Indian tamarind-based soup with spices and tomatoes.",
      imgUrl: "https://www.indianhealthyrecipes.com/wp-content/uploads/2018/11/rasam-recipe.jpg"
    },
    {
      name: "Aloo Paratha",
      chef: "Chef Kavita",
      totalRatings: 980,
      avgRating: 4.8,
      uploadedOn: "2024-03-08",
      mealType: "Breakfast",
      dishType: "Flatbread",
      testKitchenApproved: true,
      contestWinner: false,
      featured: true,
      description: "Stuffed whole wheat bread with spiced mashed potatoes, served with butter and yogurt.",
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQnQETYAyiKpjdSz6Em02Q7YgVmn4slHmui8w&s"
    },
    {
      name: "Samosa",
      chef: "Chef Arun",
      totalRatings: 1020,
      avgRating: 4.9,
      uploadedOn: "2024-01-15",
      mealType: "Snack",
      dishType: "Street Food",
      testKitchenApproved: true,
      contestWinner: true,
      featured: true,
      description: "Crispy and golden pastry filled with spiced potatoes and peas.",
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCoE1y99Mdom7djTyoP72OSHFmK3N_7HzgQg&s"
    },
    {
      name: "Malai Kofta",
      chef: "Chef Priya",
      totalRatings: 840,
      avgRating: 4.7,
      uploadedOn: "2024-02-18",
      mealType: "Dinner",
      dishType: "Curry",
      testKitchenApproved: true,
      contestWinner: false,
      featured: true,
      description: "Soft paneer and potato dumplings in a rich, creamy tomato gravy.",
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUTjHp8G7dXhcjGbGGUw5bvaxwAIefV9oQHQ&s"
    },
    {
      name: "Pani Puri",
      chef: "Chef Radhika",
      totalRatings: 1500,
      avgRating: 5.0,
      uploadedOn: "2024-03-10",
      mealType: "Snack",
      dishType: "Street Food",
      testKitchenApproved: true,
      contestWinner: true,
      featured: true,
      description: "Crispy hollow puris filled with spicy tangy water and mashed potatoes.",
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9v7mbx21rImeZHdL8RAoQ2dTLLA9fN6EzxQ&s"
    },
    {
      name: "Rabri",
      chef: "Chef Manish",
      totalRatings: 720,
      avgRating: 4.6,
      uploadedOn: "2024-02-22",
      mealType: "Dessert",
      dishType: "Sweet",
      testKitchenApproved: true,
      contestWinner: false,
      featured: false,
      description: "A rich and creamy dessert made by boiling milk until thickened and flavored with cardamom.",
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSvhVtvRHeGx4qg7cozTooizmSrvT5DRtcIw&s"
    },
    {
      name: "Besan Ladoo",
      chef: "Chef Suman",
      totalRatings: 680,
      avgRating: 4.5,
      uploadedOn: "2024-01-29",
      mealType: "Dessert",
      dishType: "Sweet",
      testKitchenApproved: true,
      contestWinner: false,
      featured: false,
      description: "Melt-in-your-mouth Indian sweet balls made with gram flour, ghee, and sugar.",
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGK0tVTEd3xWi1A-t-WIy4rronK_sCarBd-g&s"
    },
    {
        name: "Palak Paneer",
        chef: "Chef Neha",
        totalRatings: 900,
        avgRating: 4.8,
        uploadedOn: "2024-03-15",
        mealType: "Lunch",
        dishType: "Curry",
        testKitchenApproved: true,
        contestWinner: false,
        featured: true,
        description: "A nutritious spinach and paneer curry flavored with aromatic spices.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNWssGcGejWD3GjOUlWJavoQgJvPwYrgcixA&s"
    },
    {
        name: "Pav Bhaji",
        chef: "Chef Rohit",
        totalRatings: 1100,
        avgRating: 4.9,
        uploadedOn: "2024-02-12",
        mealType: "Snack",
        dishType: "Street Food",
        testKitchenApproved: true,
        contestWinner: true,
        featured: true,
        description: "A flavorful mashed vegetable curry served with buttered pav bread.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1b_FOBgouyPPDPOKpZ1KihH8in0hDNmUZvA&s"
    },
    {
        name: "Dal Tadka",
        chef: "Chef Suresh",
        totalRatings: 890,
        avgRating: 4.7,
        uploadedOn: "2024-02-28",
        mealType: "Dinner",
        dishType: "Lentil Dish",
        testKitchenApproved: true,
        contestWinner: false,
        featured: true,
        description: "Yellow lentils tempered with ghee, garlic, and Indian spices.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIX8JFszwwFRu3ccbCqGXs1MrDFB5cJNAVCA&s"
    },
    {
        name: "Dhokla",
        chef: "Chef Shruti",
        totalRatings: 750,
        avgRating: 4.6,
        uploadedOn: "2024-03-01",
        mealType: "Breakfast",
        dishType: "Snack",
        testKitchenApproved: true,
        contestWinner: false,
        featured: false,
        description: "A soft, spongy, and savory steamed cake made from fermented gram flour.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeZtCo6ri9X2Bf7RtR3IXn4iRtBMpexqUEXg&s"
    },
    {
        name: "Misal Pav",
        chef: "Chef Ananya",
        totalRatings: 920,
        avgRating: 4.8,
        uploadedOn: "2024-03-07",
        mealType: "Lunch",
        dishType: "Street Food",
        testKitchenApproved: true,
        contestWinner: true,
        featured: true,
        description: "A spicy and tangy sprout curry served with soft pav bread.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvNLpgJE419aDXhxL9qlgLukTb-d2qiGutlg&s"
    },
    {
        name: "Kheer",
        chef: "Chef Bhavana",
        totalRatings: 810,
        avgRating: 4.7,
        uploadedOn: "2024-02-17",
        mealType: "Dessert",
        dishType: "Sweet",
        testKitchenApproved: true,
        contestWinner: false,
        featured: true,
        description: "A creamy rice pudding flavored with cardamom, saffron, and nuts.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRH0hxwD3A0rtg77ANM1ZgbtlTUWv9M4VhgPA&s"
    },
    {
        name: "Shahi Tukda",
        chef: "Chef Iqbal",
        totalRatings: 730,
        avgRating: 4.6,
        uploadedOn: "2024-02-25",
        mealType: "Dessert",
        dishType: "Sweet",
        testKitchenApproved: true,
        contestWinner: false,
        featured: false,
        description: "Fried bread soaked in saffron-infused milk and garnished with nuts.",
        imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzPUBL4D417QebpVMU_AGDP-DfhZ4Dm4bb1w&s"
    },
    {
      name: "Margherita Pizza",
      chef: "Chef Antonio",
      totalRatings: 1200,
      avgRating: 4.8,
      uploadedOn: "2024-01-15",
      mealType: "Main Course",
      dishType: "Pizza",
      testKitchenApproved: true,
      contestWinner: true,
      featured: true,
      description: "Classic Italian pizza topped with fresh basil, mozzarella, and tomato sauce.",
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSauRcTuclnQCVy9XtvzdmRwpB4ppEpCs9WGw&s"
  },
  {
      name: "Seafood Soup",
      chef: "Chef Marina",
      totalRatings: 950,
      avgRating: 4.7,
      uploadedOn: "2024-03-02",
      mealType: "Starter",
      dishType: "Seafood",
      testKitchenApproved: true,
      contestWinner: false,
      featured: false,
      description: "A rich and aromatic soup with shrimp, mussels, and squid in a tomato-based broth.",
      imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4EjyJ2W5TQY1ip8kOjbYv_c3bcsVzbSO14A&s"
  },
{
    name: "Pepperoni Pizza",
    chef: "Chef Lorenzo",
    totalRatings: 1500,
    avgRating: 4.9,
    uploadedOn: "2024-01-20",
    mealType: "Main Course",
    dishType: "Pizza",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "A delicious pizza with crispy pepperoni, mozzarella, and a rich tomato sauce.",
    imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWeECgpU7ndozaDY-cS3QKLjvSL7stKvYsOQ&s"
},

{
    name: "Clam Chowder",
    chef: "Chef Fisher",
    totalRatings: 820,
    avgRating: 4.6,
    uploadedOn: "2024-02-28",
    mealType: "Starter",
    dishType: "Soup",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A creamy New England-style soup with fresh clams, potatoes, and celery.",
    imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcScu_nhY5FxNa9vZWOgYwFAaz9EO_AHVS5b5w&s"
},
{
    name: "Avocado Banana Smoothie",
    chef: "Chef Maria",
    totalRatings: 680,
    avgRating: 4.7,
    uploadedOn: "2024-02-15",
    mealType: "Beverage",
    dishType: "Smoothie",
    testKitchenApproved: true,
    contestWinner: false,
    featured: false,
    description: "A creamy and nutritious smoothie made with avocado, banana, honey, and almond milk.",
    imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ88QUnr0iFNrHue8UVe7d9U4oY0xSjcGfmMw&s"
},
{
    name: "Tacos al Pastor",
    chef: "Chef Ricardo",
    totalRatings: 1100,
    avgRating: 4.8,
    uploadedOn: "2024-02-05",
    mealType: "Main Course",
    dishType: "Mexican",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "Marinated pork tacos with pineapple, onions, and fresh cilantro, served in soft corn tortillas.",
    imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHlJj-7ghBM8zZZMujJtX7ojiC9hzI5wK1TQ&s"
},

{
    name: "Penne Alfredo",
    chef: "Chef Isabella",
    totalRatings: 1300,
    avgRating: 4.9,
    uploadedOn: "2024-01-25",
    mealType: "Main Course",
    dishType: "Italian",
    testKitchenApproved: true,
    contestWinner: true,
    featured: true,
    description: "A creamy pasta dish with a rich Alfredo sauce, topped with Parmesan cheese.",
    imgUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTavr5O66-O0khP6LzOEyzFhcpNzrHSG5Yd_w&s"
}
];

export default recipesData;
